### ISSUE TITLE
Include link/badge to Continuous Integration system used for this project

### ISSUE THREAD

**Issue by apupier** [jrichter1/vscode-extension-tester#6]
is it travis? https://github.com/jrichter1/vscode-extension-tester/blob/master/.travis.yml

I wasn't able to find it
I was expected to find it at this url which is giving a 404 https://travis-ci.org/organizations/jrichter1/vscode-extension-tester

**Comment by jrichter1** [comment]
I'm not an organization... yet :)
https://travis-ci.org/jrichter1/vscode-extension-tester

**Comment by apupier** [comment]
> I'm not an organization... yet :)

ahah stupid of me. thanks for the link. i will include the badge to it on the readme
